# #####################################################################
# Automatically generated by qmake (2.01a) Mon Feb 20 12:25:14 2012
# #####################################################################
TEMPLATE = app
RC_FILE = studytool.rc
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += studytool.h \
    studytool.h
FORMS += 
SOURCES += studytool.cpp \
    main.cpp
